/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Time_Green_Led.H
**     Project   : LEDControl
**     Processor : 56858
**     Component : TimerInt
**     Version   : Component 02.157, Driver 02.02, CPU db: 2.87.105
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2/16/2018, 12:17 PM
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TMR0123 (64-bit)
**         Compare name                : TMR0123_Compare
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 60000000 Hz
**           Initial period/frequency
**             Xtal ticks              : 4000000
**             microseconds            : 1000000
**             milliseconds            : 1000
**             seconds                 : 1
**             seconds (real)          : 1.0
**             Hz                      : 1
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TMR3_CNTR [2096797]
**              Mode                   : TMR3_CTL  [2096798]
**              Run                    : TMR3_CTL  [2096798]
**              Prescaler              : TMR3_CTL  [2096798]
**
**         Compare registers
**              Compare                : TMR3_CMP1 [2096792]
**
**         Flip-flop registers
**              Mode                   : TMR3_CTL  [2096798]
**     Contents  :
**         No public methods
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __Time_Green_Led
#define __Time_Green_Led

/* MODULE Time_Green_Led. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


void Time_Green_Led_Init(void);
/*
** ===================================================================
**     Method      :  Time_Green_Led_Init (component TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void Time_Green_Led_Interrupt(void);
/*
** ===================================================================
**     Method      :  Time_Green_Led_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END Time_Green_Led. */

#endif /* ifndef __Time_Green_Led */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
