/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LED1.C
**     Project   : Echo
**     Processor : 56858
**     Component : Led
**     Version   : Component 01.007, Driver 01.06, CPU db: 2.87.105
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2/23/2018, 2:09 PM
**     Abstract  :
**          This bean provide methods for driving of LED device.
**          Methods On, Off, Set and Toggle (or only initialization code)
**          could be used to drive it. Output value, defined by Init.
**          value property, is used for initialization implicitly.
**          It is not necessary to use any method explicitly in start up.
**          Method Status return current status of the LED device.
**          LED drivers without output inverter are supported
**          via Inverted value property.
**     Settings  :
**          Output PIN                                     :GPIOD5_SC12
**          Initialize Value                               :Off
**          Inverted Value                                 :no
**     Contents  :
**         On     - void LED1_On(void);
**         Toggle - void LED1_Toggle(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE LED1. */

#include "LED1.h"

/*
** ===================================================================
**     Method      :  LED1_On (component Led)
**
**     Description :
**         Switch ON the LED device
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_On(void)
{
  // This function is implemented as a macro
}
*/

/*
** ===================================================================
**     Method      :  LED1_Toggle (component Led)
**
**     Description :
**         Toggle the LED device value
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED1_Toggle(void)
{
  // This function is implemented as a macro
}
*/

/* END LED1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
