/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Codec.C
**     Project   : Echo1
**     Processor : 56858
**     Component : Audio_Codec_CS4218
**     Version   : Component 01.041, Driver 01.04, CPU db: 2.87.105
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2/23/2018, 1:58 PM
**     Abstract  :
**         This bean implements an 16-Bit Stereo Audio Codec CS4218.
**         The CS4218 is a monolithic CMOS device for for computer
**         multimedia, automotive, and portable audio applications.
**         It performs A/D and D/A conversion, filtering, and level
**         setting, creating 4 audio inputs and 2 audio outputs for
**         a digital computer system. The digital interfaces of left
**         and right channels are multiplexed into a single serial
**         data bus with word rates up to 50 kHz per channel.
**     Settings  :
**         Type of Audio Codec        : CS4218
**         Selected device            : CODEC 0
**         Serial Intefrace Mode      : Serial mode 4
**         HW Interface
**           SSI                      : FreescaleSSI   (ESSI0)
**           RST                      : BitIO_Out      (GPIOC4_SC01)
**           CCLK                     : BitIO_Out      (GPIOE3_TXD1)
**           CCS                      : BitIO_Out      (GPIOC3_SC00)
**           CDIN                     : BitIO_Out      (GPIOE2_RXD1)
**         Fifo size                  : 32
**         Mode                       : STEREO
**         Mute                       : Disabled
**         Left Attenuation           : 0.0    [dB]
**         Right Attenuation          : 0.0    [dB]
**         Left Gain                  : 10.5   [dB]
**         Right Gain                 : 10.5   [dB]
**         Enabled in init. code      : yes
**         Events enabled in init.    : no
**     Contents  :
**         Enable  - byte Codec_Enable(void);
**         Disable - byte Codec_Disable(void);
**         Read    - byte Codec_Read(const void* pBuffer, word nBytes, word *Rcv);
**         Write   - byte Codec_Write(const void* pBuffer, word nBytes, word *Snd);
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Codec. */

#include "Codec.h"
codec_sCfgCS4215 codecdrvDevice0Cfg =
{
  CODEC_RX_CONTROL_WORD,
  CODEC_TX_CONTROL_WORD
};

word CodecRxConfig;
word CodecTxConfig;

#define TX_CONTROL_BITS        13
#define RX_CONTROL_BITS        11
#define UNUSED_CONTROL_BITS     8

static dword codecConfig(word RxConfig,word TxConfig);
static void delay(void);

static bool EnUser;
/*
** ===================================================================
**     Method      :  Codec_Enable (component Audio_Codec_CS4218)
**
**     Description :
**         Enable the bean - (Enable the Freescale SSI interface).
**     Parameters  : None
**     Returns     :
**         ---             - This method returns error codes from
**                           Enable method of inherited FreescaleSSI
**                           bean.
** ===================================================================
*/
byte Codec_Enable(void)
{
  EnUser = TRUE;
  return(Inhr2_Enable());
}

/*
** ===================================================================
**     Method      :  Codec_Disable (component Audio_Codec_CS4218)
**
**     Description :
**         Disable the bean - (Disable the Freescale SSI interface).
**     Parameters  : None
**     Returns     :
**         ---             - This method returns error codes from
**                           Disable method of inherited FreescaleSSI
**                           bean.
** ===================================================================
*/
byte Codec_Disable(void)
{
  EnUser = FALSE;
  return(Inhr2_Disable());
}

/*
** ===================================================================
**     Method      :  Codec_Read (component Audio_Codec_CS4218)
**
**     Description :
**         This method reads data from the SSI interface.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pBuffer         - Pointer to the block of
**                           received data
**         nBytes          - Size of the block in bytes
**       * Rcv             - Pointer to real number of the received
**                           data
**     Returns     :
**         ---             - This method returns error codes from
**                           ReciveBlock method of inherited
**                           FreescaleSSI bean.
** ===================================================================
*/
byte Codec_Read(const void* pBuffer,word nBytes,word *Rcv)
{
  byte        err;
  word        Bytes;
  UWord16     SamplesRead = 0;
  word        NumSamplesReq = nBytes >> 1;

  if(!EnUser) Codec_Enable();
  do
  {
    err = Inhr2_RecvBlock((word*)pBuffer+SamplesRead,
                                     NumSamplesReq-SamplesRead,
                                     &Bytes);
    SamplesRead += Bytes;
  } while(SamplesRead < NumSamplesReq);
  *Rcv = SamplesRead << 1;
  return err;
}

/*
** ===================================================================
**     Method      :  Codec_Write (component Audio_Codec_CS4218)
**
**     Description :
**         Send a block of characters to the SSI interface.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pBuffer         - Pointer to the block of data to
**                           write
**         nBytes          - Size of the block in bytes
**       * Snd             - Pointer to number of data that are
**                           writen (moved to buffer)
**     Returns     :
**         ---             - This method returns error codes from
**                           SendBlock method of inherited
**                           FreescaleSSI bean.
** ===================================================================
*/
byte Codec_Write(const void* pBuffer,word nBytes,word *Snd)
{
  byte        err;
  word        Bytes = 0;
  UWord16     NumSamplesWritten = 0;
  Word16      * pSamplesBuffer = (Word16 *) pBuffer;
  word        NumSamplesReq = nBytes >> 1;

  if(!EnUser) Codec_Enable();
  do
  {
    err = Inhr2_SendBlock((word*)pSamplesBuffer + NumSamplesWritten,
                               NumSamplesReq - NumSamplesWritten,
                               &Bytes);
    NumSamplesWritten += Bytes;
  } while(NumSamplesWritten < NumSamplesReq);
  *Snd = NumSamplesWritten << 1;
  return err;
}

/*
** ===================================================================
**     Method      :  delay (component Audio_Codec_CS4218)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void delay(void)
{
  unsigned int i;

  for (i = 0; i<6; i++) {
    asm(nop);
  }
}

/*
** ===================================================================
**     Method      :  Codec_codecInit (component Audio_Codec_CS4218)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Codec_codecInit(void)
{
  /* Initialize CCLK to low */
  Inhr4_ClrVal();
  EnUser = TRUE;
  /* Start SSI interface */
  Inhr2_Enable();
  /* Reset the codec */
  Inhr3_ClrVal();
  delay();                             /* Delay for timing requirements */
  Inhr3_SetVal();
  /* Initialize the codec
  The CS4218 requires a dummy write to the control section followed by the actual
  write to the control section.
  This is done with two consecutive calls to codecConfig()*/
  (void)codecConfig(CODEC_RX_CONTROL_WORD, CODEC_TX_CONTROL_WORD);
  (void)codecConfig(CODEC_RX_CONTROL_WORD, CODEC_TX_CONTROL_WORD);
}

/*
** ===================================================================
**     Method      :  codecConfig (component Audio_Codec_CS4218)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static dword codecConfig(word RxConfig,word TxConfig)
{
  int i;

  /* The CS4218 codec in mode 4 requires 32 bits of control data
  to be transmitted to the codec.  the first 13 bits contain
  configuration information for the transmit section.  the
  next 11 bits contain configuration information for the
  receive section.  The last 8 bits are unused, but must be
  transmitted. */

  /* Save latest settings for ioctl routines which may change them */
  CodecRxConfig = RxConfig;
  CodecTxConfig = TxConfig;
  /* Initialize clock */
  Inhr4_ClrVal();                      /* Clock low */
  Inhr5_ClrVal();                      /* Chip select */
  /* Clock in the transmit control bits */
  for (i=TX_CONTROL_BITS-1; i>=0; i--) {
    Inhr4_SetVal();                    /* Clock higt */
    delay();                           /* Delay for timing requirements */
    if (((TxConfig >> i) & 0x0001) != 0) {
      Inhr6_SetVal();                  /* Data = 1 */
    }
    else {
      Inhr6_ClrVal();                  /* Data = 0 */
    }
    delay();                           /* Delay for timing requirements */
    Inhr4_ClrVal();                    /* Clock low */
    delay();                           /* Delay for timing requirements */
  }
  /* Clock in the receive control bits */
  for (i=RX_CONTROL_BITS-1; i>=0; i--) {
    Inhr4_SetVal();                    /* Clock high */
    delay();                           /* Delay for timing requirements */
    if (((RxConfig >> i) & 0x0001) != 0) {
      Inhr6_SetVal();                  /* Data = 1 */
    }
    else {
      Inhr6_ClrVal();                  /* Data = 0 */
    }
    delay();                           /* Delay for timing requirements */
    Inhr4_ClrVal();                    /* Clock low */
    delay();                           /* Delay for timing requirements */
  }
  /* Clock in the unused control bits */
  for (i=UNUSED_CONTROL_BITS-1; i>=0; i--)
  {
    Inhr4_SetVal();                    /* Clock high */
    delay();                           /* Delay for timing requirements */
    Inhr6_ClrVal();                    /* Data = 0 */
    delay();                           /* Delay for timing requirements */
    Inhr4_ClrVal();                    /* Clock low */
    delay();                           /* Delay for timing requirements */
  }
  Inhr5_SetVal();                      /* Chip deselect */
  return(0);
}

/* END Codec. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
