/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TI1.C
**     Project   : Combo
**     Processor : 56858
**     Component : TimerInt
**     Version   : Component 02.157, Driver 02.02, CPU db: 2.87.105
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2/16/2018, 4:17 PM
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TMR0123 (64-bit)
**         Compare name                : TMR0123_Compare
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**           Initial period/frequency
**             Xtal ticks              : 1000000
**             microseconds            : 250000
**             milliseconds            : 250
**             seconds (real)          : 0.25
**             Hz                      : 4
**
**         Runtime setting             : modes (list of settings)
**            -----------------------------------------------------------------------
**            |  period  |     Prescaler      |        Real period [seconds]        |
**     --------    or    |-----------------------------------------------------------
**     | mode | freqency | high | low  | slow |    high    |    low     |    slow   |
**     ------------------------------------------------------------------------------
**     |  0   |  0_25sec | 1    | -    | -    | 0.25       | -          | -         |
**     |  1   |  0_5sec  | 1    | -    | -    | 0.5        | -          | -         |
**     |  2   |  0_75sec | 1    | -    | -    | 0.75       | -          | -         |
**     |  3   |  1sec    | 1    | -    | -    | 1.0        | -          | -         |
**     ------------------------------------------------------------------------------
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TMR3_CNTR [2096797]
**              Mode                   : TMR3_CTL  [2096798]
**              Run                    : TMR3_CTL  [2096798]
**              Prescaler              : TMR3_CTL  [2096798]
**
**         Compare registers
**              Compare                : TMR3_CMP1 [2096792]
**
**         Flip-flop registers
**              Mode                   : TMR3_CTL  [2096798]
**     Contents  :
**         SetPeriodMode - byte TI1_SetPeriodMode(byte Mode);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE TI1. */

#include "Events.h"
#include "TI1.h"

static bool EnUser;                    /* Enable/Disable device by user */
static byte TMode;                     /* Number of actual timer modes */


/* Table of compare register values for high speed CPU mode */
static const word HighComp0[4] = {46874,46874,46874,46874};
static const word HighComp1[4] = {319,639,959,1279};
static const word HighComp2[4] = {0,0,0,0};
static const word HighComp3[4] = {0,0,0,0};

/* Internal method prototypes */
static void HWEnDi(void);
static void SetCV(word Val0, word Val1, word Val2, word Val3);
static void SetPV(byte Val);

/*
** ===================================================================
**     Method      :  SetCV (component TimerInt)
**
**     Description :
**         Sets compare or preload register value. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetCV(word Val0, word Val1, word Val2, word Val3)
{
  EnterCritical();                     /* Disable global interrupts */
  setReg(TMR3_CMP1,Val3);              /* Store given value to the compare registers */
  setReg(TMR2_CMP1,Val2);
  setReg(TMR1_CMP1,Val1);
  setReg(TMR0_CMP1,Val0);
  ExitCritical();                      /* Enable global interrupts */
}

/*
** ===================================================================
**     Method      :  SetPV (component TimerInt)
**
**     Description :
**         Sets prescaler value. The method is called automatically as a 
**         part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetPV(byte Val)
{
  EnterCritical();                     /* Disable global interrupts */
  setRegBitGroup(TMR0_CTL,PCS,Val);    /* Store given value to the prescaler */
  setReg(TMR0_CNTR,0);                 /* Reset counter */
  setReg(TMR1_CNTR,0);
  setReg(TMR2_CNTR,0);
  setReg(TMR3_CNTR,0);
  ExitCritical();                      /* Enable global interrupts */
}

/*
** ===================================================================
**     Method      :  HWEnDi (component TimerInt)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setRegBitGroup(TMR0_CTL,CM,1);     /* Run counter */
  }
  else {                               /* Disable device? */
    setRegBitGroup(TMR0_CTL,CM,0);     /* Stop counter */
    setReg(TMR0_CNTR,0);               /* Reset counter */
    setReg(TMR1_CNTR,0);
    setReg(TMR2_CNTR,0);
    setReg(TMR3_CNTR,0);
  }
}

/*
** ===================================================================
**     Method      :  TI1_SetPeriodMode (component TimerInt)
**
**     Description :
**         Switches the bean to a specified mode (changes the period/frequency
**         using the mode values). This method reduces the time needed
**         for setting of a new period value. This method can be used only when
**         a list of possible period settings is specified at design time.
**         Each of these settings constitutes a mode and Processor Expert
**         assigns them a mode identifier. The prescaler and compare values
**         corresponding to each mode are calculated at design time.
**         Modes can be switched at runtime just by referring to a mode
**         identifier. No run-time calculations are performed, all the
**         calculations are performed at design time. The modes and mode
**         identifiers may be found in the include file *.h.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Mode              Mode to switch to (0 to 3)
**                           TI1_PM_0_25sec
**                           TI1_PM_0_5sec
**                           TI1_PM_0_75sec
**                           TI1_PM_1sec
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_VALUE - Value out of range,
**                           requested timing mode is not defined
** ===================================================================
*/
byte TI1_SetPeriodMode(byte Mode)
{
  bool TmrRun;                         /* Temporary flag enable/disable */

  if (Mode > 3) {                      /* Is a values of mode identifier out of range? */
    return ERR_VALUE;                  /* If yes then error */
  }
  TmrRun = EnUser;                     /* Store actual device state */
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Enable/disable device according to status flags */
  }
  TMode = Mode;                        /* Store given mode identifier to the variable TMode */
  SetCV(HighComp0[Mode],HighComp1[Mode],HighComp2[Mode],HighComp3[Mode]); /* Store appropriate values to the compare registers according to the value of mode identifier if selected high speed CPU mode */
  if (TmrRun) {                        /* Was the device disabled? */
    EnUser=TRUE;                       /* If yes set flag "device enabled" */
    HWEnDi();                          /* Enable/disable device according to status flags */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TI1_Init (component TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void TI1_Init(void)
{
  /* TMR0_CTL: CM=0,PCS=0,SCS=0,ONCE=0,LENGTH=1,DIR=0,EXT_INIT=0,OM=0 */
  setReg(TMR0_CTL,32);                 /* Stop all functions of the timer */
  /* TMR1_CTL: CM=7,PCS=4,SCS=0,ONCE=0,LENGTH=1,DIR=0,EXT_INIT=0,OM=0 */
  setReg(TMR1_CTL,59424);
  /* TMR2_CTL: CM=7,PCS=5,SCS=0,ONCE=0,LENGTH=1,DIR=0,EXT_INIT=0,OM=0 */
  setReg(TMR2_CTL,59936);
  /* TMR3_CTL: CM=7,PCS=6,SCS=0,ONCE=0,LENGTH=1,DIR=0,EXT_INIT=0,OM=0 */
  setReg(TMR3_CTL,60448);              /* Set up cascade counter mode */
  /* TMR3_SCR: TCF=0,TCFIE=1,TOF=0,TOFIE=0,IEF=0,IEFIE=0,IPS=0,INPUT=0,Capture_Mode=0,MSTR=0,EEOF=0,VAL=0,FORCE=0,OPS=0,OEN=0 */
  setReg(TMR3_SCR,16384);
  /* TMR2_SCR: TCF=0,TCFIE=0,TOF=0,TOFIE=0,IEF=0,IEFIE=0,IPS=0,INPUT=0,Capture_Mode=0,MSTR=0,EEOF=0,VAL=0,FORCE=0,OPS=0,OEN=0 */
  setReg(TMR2_SCR,0);
  /* TMR1_SCR: TCF=0,TCFIE=0,TOF=0,TOFIE=0,IEF=0,IEFIE=0,IPS=0,INPUT=0,Capture_Mode=0,MSTR=0,EEOF=0,VAL=0,FORCE=0,OPS=0,OEN=0 */
  setReg(TMR1_SCR,0);
  /* TMR0_SCR: TCF=0,TCFIE=0,TOF=0,TOFIE=0,IEF=0,IEFIE=0,IPS=0,INPUT=0,Capture_Mode=0,MSTR=0,EEOF=0,VAL=0,FORCE=0,OPS=0,OEN=0 */
  setReg(TMR0_SCR,0);
  setReg(TMR3_CNTR,0);                 /* Reset counter register */
  setReg(TMR2_CNTR,0);
  setReg(TMR1_CNTR,0);
  setReg(TMR0_CNTR,0);
  setReg(TMR3_LOAD,0);                 /* Reset load register */
  setReg(TMR2_LOAD,0);
  setReg(TMR1_LOAD,0);
  setReg(TMR0_LOAD,0);
  TMode = 0;                           /* Set number of actual timer mode to 0 */
  EnUser = TRUE;                       /* Enable device */
  SetCV(HighComp0[TMode],HighComp1[TMode],HighComp2[TMode],HighComp3[TMode]); /* Store appropriate values to the compare registers according to the value of mode identifier if selected high speed CPU mode */
  SetPV((byte)8);                      /* Set prescaler register according to the selected high speed CPU mode */
  HWEnDi();                            /* Enable/disable device according to status flags */
}

/*
** ===================================================================
**     Method      :  TI1_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp saveall
void TI1_Interrupt(void)
{
  clrRegBit(TMR3_SCR,TCF);             /* Reset interrupt request flag */
  TI1_OnInterrupt();                   /* Invoke user event */
}

/* END TI1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
